from sys import stdout as s
from time import sleep as j
import sys

def w(print):
  for i in print:
    j(.03)
    s.write(i)
    s.flush()
  next = input()
def noinput(print):
  for i in print:
    j(.03)
    s.write(i)
    s.flush()
w("Hello, and welcome back!")
w("You might remember last time that we learned about printing out, equations, and variables.")
w('Today we will be learning something similar.')
w("We will be learning these 3 topics today:\n- Multiple-value Variables\nF-strings\nUser inputs")
w("First, open a new Python repl using the same steps as last time.")
w("Multiple-value variables are just regular variables, except they can store multiple values.")
w("To make one, you must use brackets.\nExample:\nnames = ['Joe','Bob','Sally']")
w("Notice that you must put a comma between each name.")
w("To print it out, use the same as last time\nprint(names)")
w("It still includes the square brackets.")
w("To remove them, simply do this:\n variablename2 = str(variablename)[1:-1]\nprint(variablename2)")
w("If you do that before printing the variable out, you can see that it doesn't show brackets.")
w("There is also a way of printing out a single name in a list of names.")
w("To do this, do print(variablename[number])")
w("Please remember to put the square bracket in the number.")
w("Which number to choose? The first value is 0, the next is 1, and so on.")
w("You can also count backwards.")
w("The last one is -1, The 2nd last is -2, and so on")
w("That concludes multi-value variables.")
w("Let's move on to f strings.")
w("Remember how you print(variablename)?")
w("Well, there's another way of doing it.")
w("It's also more efficent and easier to understand than using a comma or plus sign.")
w("Making one is simple.")
w("Before you do the ' sign, you must put an f. Example\nname = 'Bob'\nprint(f'My name is {name}')")
w("When you do a variable, you must put squiggly brackets {}")
w("That concludes f strings.")
w("Next thing is user inputs.")
w("Inputs are when the program asks you a question.")
w("When they ask that question, it is stored in a variable.")
w("For example, I can write:\nname = input('What is your name?')")
w("This will ask you your name, and you can respond.")
w("It will store your name in the variable called 'name'")
w("Printing out an input is the same as a variable, doing print(variablename) or using an f string.")
w("Example:\nname = input('What is your name?')\nprint(f'Hello, {name}')")
w("That concludes our lesson!")
w("If you have any questions, please comment at: https://repl.it/@stoporinjail/Python-Lessons\nThank you!")